### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by goodcyg** [fenglh/MachoView#1]
运行报错：ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)

**Comment by coderchou** [comment]
可以编译成功，但是打不开

**Comment by fenglh** [comment]
> 可以编译成功，但是打不开

首次打开是没有界面的，菜单-open 选择mac-o文件即可

**Comment by fenglh** [comment]
> 运行报错：ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)

不影响使用，菜单-open 选择mac-o文件即可
